name: Update LLMs

on:
  push:
    branches:
      - main
    paths:
      - README.md
  pull_request:
    branches:
      - main
    paths:
      - README.md

permissions:
  contents: write

jobs:
  update-llms-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: Install docs2llms
        run: |
          deno install -n docs2llms https://jsr.io/@jurajstefanic/docs2llms/0.0.1/mod.ts --allow-read --allow-net --allow-write --allow-run --global -f

      - name: Update LLMs
        run: docs2llms --local . --exclude rst,txt --skip example

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add llms.txt llms-full.txt
          git commit -m "chore: update llms.txt and llms-full.txt"
          git push
        continue-on-error: true
